version: '3.8'

services:
  # Laravel PHP app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel

  # Nginx
  web:
    image: nginx:latest
    container_name: laravel_nginx
    restart: always
    ports:
      - "8080:80"   # Laravel accessible on localhost:8080
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # MySQL
  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"   # Avoid conflict with local MySQL
    networks:
      - laravel

  # SonarQube for code quality
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"   # Access via localhost:9000
    networks:
      - laravel

  # Nexus Repository
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    ports:
      - "8081:8081"   # Access via localhost:8081
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
