name: Laravel SonarQube Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sonar:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, intl, pdo, mysql
          ini-file: production
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist
        shell: powershell
